Update the Hello App following the latest specifications
launchdarkly/hello-ruby pull request #12
Opened 2024-04-15 23:44 UTC by louis-launchdarkly

See the spec referred in https://github.com/launchdarkly/sdk-specs/pull/52

2024-04-18 17:52 UTC, keelerm84 requested changes

2024-04-18 17:52 UTC, keelerm84 commented on main.rb
> +  if flag_value
This will show the logo each time it switches to true instead of only the initial time, right? I don't think that aligns with the spec.

2024-04-18 17:52 UTC, keelerm84 commented on main.rb
> +end
Ruby has this nice little shorthand you can use.

```suggestion
exit 0 if ci
```

2024-04-18 17:52 UTC, keelerm84 commented on main.rb
> +# Run the Hello App continously to react to flag change in LaunchDarkly
```suggestion
# Run the Hello App continuously to react to flag change in LaunchDarkly
```

2024-04-22 06:34 UTC, louis-launchdarkly commented on main.rb
> +  if flag_value
Let me ask project quickstart refresh channel - I was thinking whenever it turns to true (but I added the word 'once' at the end of Requirement 1.4.2).

2024-04-23 05:44 UTC, louis-launchdarkly commented on main.rb
> +  if flag_value
After clarification, this should be good.

2024-04-23 16:48 UTC, keelerm84 approved these changes

2024-04-23 17:59 UTC, merged